### ISSUE TITLE
NetworkPolicy v1 -> MultiPort

### ISSUE THREAD

**Issue by rikatz** [jayunit100/network-policy-subproject#21]
Issue to track the creation of a proposal/PR for a KEP to add a new field into NetworkPolicy, as

```yaml
  portRange
  - from: 32000
    to: 35000
  - from: 44000
    to: 45000
```

Example use case: https://docs.google.com/document/d/1AtWQy2fNa4qXRag9cCp5_HsefD7bxKe3ea2RPn8jnSs/edit#bookmark=id.k7sy1l76o8br

Ports exception maybe is a different step/proposal. This one tries to solve cases as FTP with active mode, WebRTC stuff and other things that uses port ranges.
