### ISSUE TITLE
[User story proposal] add a name or description to a NetworkPolicy rule

### ISSUE THREAD

**Issue by jianjuns** [jayunit100/network-policy-subproject#28]
I want to add an name or description string to a single NetworkPolicy rule in the NetworkPolicy spec, which helps me to remember the rule, and also helps visualization and analytics of NetworkPolicy rules from an external console or policy/traffic analyzer.

A readable string can help users to remember and understand the rules, and can also be used to identify a rule in the exported policy metrics and network flows (when the NetworkPolicy and rule information is appended to the metrics or flow records).

@McCodeman @abhiraut

**Comment by jayunit100** [comment]
So you could always make an annotation on the object right? 

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    casey: calico
    jayunit100: everything
    jiunjen: antrea
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      unique: "8"
  policyTypes:
  - Ingress
```
